version: '3.3'

services:
 mysql:
   image: mysql:8.0.19
   ports: 
    - 3307:3306
   volumes: 
    - ./sql_data:/var/lib/mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: quizdb
    MYSQL_USER: quizmaster
    MYSQL_PASSWORD: 123456
